version: 2
jobs:
  build:
    docker:
      - image: python:3.5.5
    steps:
      - checkout
      - run:
          name: 'Setup virtualenv'
          command: |
            mkdir -p ~/.virtualenvs
            python3 -m venv ~/.virtualenvs/target-stitch
            source ~/.virtualenvs/target-stitch/bin/activate
            pip install -U pip setuptools
            pip install -U pylint
            pip install -e .[dev]
      - run:
          name: 'Run tests'
          command: |
            # Need to re-activate the virtualenv
            source ~/.virtualenvs/target-stitch/bin/activate
            nosetests --ignore-files=integration_tests.py
            pylint target_stitch
